services:
  redis:
    image: 'redis:7.2-alpine'
    ports:
      - '6379:6379'
    environment:
      TZ: 'Australia/Perth'
  postgres15:
    image: 'postgis/postgis:15-3.5-alpine'
    ports:
      - '5432:5432'
    environment:
      TZ: 'Australia/Perth'
    volumes:
      - 'postgres15:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']

volumes:
  postgres15:
